Background client
vostok/graphiteclient pull request #2
Opened 2017-11-10 12:17 UTC by ezsilmar

Resolves https://github.com/vostok/graphiteclient/issues/1
Need to fix metrics consumer in https://github.com/vostok/airlock.consumer after this one is merged.

2017-12-20 10:46 UTC, trurl123 commented on Vostok.Graphite.Client/Metric.cs
> +            return new MetricSerializer().Serialize(this);
почему нельзя сделать MetricSerializer.Serialize статичным?

2017-12-20 10:57 UTC, trurl123 commented on Vostok.Graphite.Client/Metric.cs
> +        /// <para>Inside a segment only a-zA-Z0-9_ chars are valid</para>
"Only a-zA-Z0-9_ chars are valid inside a segment"  - так звучит более естественно

2017-12-20 11:58 UTC, trurl123 commented on Vostok.Graphite.Client/GraphiteClient.cs
> +            while ((handle = TryGetHandle()) != null)
это нормально, что тут бесконечный цикл?

2017-12-20 12:10 UTC, trurl123 commented on Vostok.Graphite.Client/MetricSendDaemon.cs
> +        private const int NotStarted = 0;
У нас в проекте вроде настройки private const начинается с маленькой буквы. У тебя не подчеркивает решарпер?

2017-12-20 12:30 UTC, trurl123 requested changes
См. комменты. Самое непонятное, почему появился бесконечный цикл в GraphiteClient

2017-12-20 12:31 UTC, trurl123 commented
это получается только частичное решение для отправки метрик из консьюмеров?
я не понял как сделать так, чтобы IMetricScope отправлял напрямую минуя AirlockClient?

2017-12-20 12:48 UTC, trurl123 commented on Vostok.Graphite.Client/Metric.cs
> +                        throw new ArgumentException($"Metric can't have segment with zero length. Position ${i}: {name}");
я бы так написал:
Metric segment could not be zero length

2017-12-20 12:56 UTC, trurl123 commented on Vostok.Graphite.Client/Metric.cs
> +                throw new ArgumentException("Metric name can't be null or have zero length");
я бы так написал:
Metric name could not be null or empty

2017-12-21 08:06 UTC, trurl123 commented on Vostok.Graphite.Client/GraphiteClient.cs
> +                    await connection.SendAsync(metrics).ConfigureAwait(false);
Получается, что при ошибке в этой строке handle не будет диспозиться и также возникает вероятность двойного перебора IEnumerable<Metric>, что тоже может привести к ошибке.

2017-12-22 05:59 UTC, ezsilmar commented on Vostok.Graphite.Client/Metric.cs
> +            return new MetricSerializer().Serialize(this);
А зачем делать его статичным? Ну и сейчас у него StringBuilder внутри

2017-12-22 05:59 UTC, ezsilmar commented on Vostok.Graphite.Client/Metric.cs
> +        /// <para>Inside a segment only a-zA-Z0-9_ chars are valid</para>
Fixed

2017-12-22 05:59 UTC, ezsilmar commented on Vostok.Graphite.Client/GraphiteClient.cs
> +            while ((handle = TryGetHandle()) != null)
К каким непонятным зависаниям он может привести? 
Этот цикл нужен на случай, если в пуле окажутся дохлые tcp-соединения. Если ты смог достать живое из пула или переподключиться, то почему бы не послать данных в стрим. Если хотя бы один раз не смог переподключиться, то мы не будем еще раз пытаться - что-то пошло не так.

2017-12-22 05:59 UTC, ezsilmar commented on Vostok.Graphite.Client/MetricSendDaemon.cs
> +        private const int NotStarted = 0;
Сейчас подчеркивает. Fixed
Пиши коммит-месседжи на английском, пожалуйста :)

2017-12-22 05:59 UTC, ezsilmar commented on Vostok.Graphite.Client/GraphiteClient.cs
> +                    await connection.SendAsync(metrics).ConfigureAwait(false);
Это сделано намеренно: если у тебя случилась ошибка при Send-е, значит с соединением что-то не так. Его нельзя переиспользовать. Заметь, что в этом случае мы не диспоузим только хэндл: tcp-соединение освобождается.

Насчет перебора IEnumerable - сделал IReadOnlyCollection

2017-12-22 06:38 UTC, trurl123 commented on Vostok.Graphite.Client/MetricSendDaemon.cs
> +        private const int NotStarted = 0;
ок, надо бы

2017-12-22 06:39 UTC, trurl123 approved these changes

2018-01-11 09:14 UTC, merged